[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from = "/dem-eigenen-folgen"
  to = "/wirklich-deins/"
  status = 301
  force = true

[[redirects]]
  from = "/dem-eigenen-folgen/"
  to = "/wirklich-deins/"
  status = 301
  force = true

[[redirects]]
  from = "http://petrasailer.com/*"
  to = "https://petrasailer.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.petrasailer.com/*"
  to = "https://petrasailer.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.petrasailer.com/*"
  to = "https://petrasailer.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/:route/index.html"
  to = "/:route/"
  status = 301
  force = true

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=3600"
