[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from = "/dem-eigenen-folgen"
  to = "/wirklich-deins/"
  status = 301
  force = true
